# Generated by Django 3.2.9 on 2021-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.IntegerField(help_text='Количество месяцев')),
                ('education', models.CharField(max_length=100)),
                ('scores', models.JSONField()),
                ('preferences', models.JSONField()),
            ],
        ),
    ]
