# Generated by Django 4.0.2 on 2022-02-28 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0002_scoringresult_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringresult',
            options={'verbose_name': 'scoring result', 'verbose_name_plural': 'scoring results'},
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
