# Generated by Django 4.0.3 on 2022-03-13 12:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_company_description_alter_company_profile_and_more'),
        ('scoring', '0003_alter_scoringresult_options_scoringresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringresult',
            name='company',
        ),
        migrations.RemoveField(
            model_name='scoringresult',
            name='education',
        ),
        migrations.RemoveField(
            model_name='scoringresult',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='scoringresult',
            name='position',
        ),
        migrations.RemoveField(
            model_name='scoringresult',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='scoringresult',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='scoringresult',
            name='scores',
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='profiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['null'], size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('experience', models.IntegerField(help_text='Количество месяцев')),
                ('education', models.CharField(max_length=100)),
                ('scores', models.JSONField()),
                ('preferences', models.JSONField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scoring result',
                'verbose_name_plural': 'scoring results',
            },
        ),
        migrations.AddField(
            model_name='scoringresult',
            name='formResult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='scoring.formresult'),
        ),
    ]
