# Generated by Django 4.0.3 on 2022-03-13 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('scoring', '0004_remove_scoringresult_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresult',
            options={'verbose_name': 'form result', 'verbose_name_plural': 'form results'},
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='company',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='education',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='position',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='formresult',
            name='scores',
        ),
        migrations.AddField(
            model_name='formresult',
            name='additional',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='formresult',
            name='career_area',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='formresult',
            name='competitions',
            field=models.ManyToManyField(related_name='FormResults', to='main.event'),
        ),
        migrations.AddField(
            model_name='formresult',
            name='jobs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresult',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
