# Generated by Django 4.0.3 on 2022-03-13 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0005_alter_formresult_options_remove_formresult_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresult',
            name='competitions',
        ),
        migrations.AddField(
            model_name='formresult',
            name='competitions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoringresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
