# Generated by Django 4.0.2 on 2022-02-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_scoringresult_options_scoringresult_user'),
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AlterField(
            model_name='article',
            name='relatedArticles',
            field=models.ManyToManyField(to='recommendations.Article'),
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(to='recommendations.Article')),
                ('courses', models.ManyToManyField(to='recommendations.Course')),
                ('events', models.ManyToManyField(to='recommendations.Event')),
                ('scoringResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.scoringresult')),
                ('vacancies', models.ManyToManyField(to='recommendations.Vacancy')),
            ],
            options={
                'verbose_name': 'recommendation result',
                'verbose_name_plural': 'recommendation results',
            },
        ),
    ]
