# Generated by Django 4.0.2 on 2022-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_article_description_alter_article_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='relatedArticles',
            field=models.ManyToManyField(to='recommendations.Article'),
        ),
        migrations.AlterField(
            model_name='recommendationresult',
            name='articles',
            field=models.ManyToManyField(to='recommendations.Article'),
        ),
        migrations.AlterField(
            model_name='recommendationresult',
            name='courses',
            field=models.ManyToManyField(to='recommendations.Course'),
        ),
        migrations.AlterField(
            model_name='recommendationresult',
            name='events',
            field=models.ManyToManyField(to='recommendations.Event'),
        ),
        migrations.AlterField(
            model_name='recommendationresult',
            name='vacancies',
            field=models.ManyToManyField(to='recommendations.Vacancy'),
        ),
    ]
