# Generated by Django 4.0.2 on 2022-02-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_alter_article_name_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='profile',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='profile',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profession',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profile',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
