# Generated by Django 4.0.3 on 2022-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_remove_article_relatedarticles_and_more'),
        ('recommendations', '0010_alter_recommendationresult_scoringresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relatedArticles',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='event',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.DeleteModel(
            name='recommendationresult',
        ),

        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
