# Generated by Django 4.0.3 on 2022-03-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0005_alter_formresult_options_remove_formresult_company_and_more'),
        ('main', '0004_remove_article_relatedarticles_and_more'),
        ('recommendations', '0011_remove_article_relatedarticles_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(related_name='recommendations', to='main.article')),
                ('courses', models.ManyToManyField(related_name='recommendations', to='main.course')),
                ('events', models.ManyToManyField(related_name='recommendations', to='main.event')),
                ('scoringResult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='scoring.scoringresult')),
                ('vacancies', models.ManyToManyField(related_name='recommendations', to='main.vacancy')),
            ],
            options={
                'verbose_name': 'recommendation result',
                'verbose_name_plural': 'recommendation results',
            },
        ),
    ]
