# Generated by Django 4.0.3 on 2022-03-13 12:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_company_description_alter_company_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('profile', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('link', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('profile', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('link', models.CharField(max_length=500, null=True)),
                ('profession', models.CharField(max_length=500, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField(help_text='Количество месяцев', null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('shift', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('profile', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('link', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('profile', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('link', models.CharField(max_length=500, null=True)),
                ('rubric', models.CharField(max_length=100, null=True)),
                ('relatedArticles', models.ManyToManyField(to='main.article')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
