# Generated by Django 4.0.3 on 2022-03-13 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_relatedarticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relatedArticles',
        ),
        migrations.AddField(
            model_name='article',
            name='relatedArticles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
