# Generated by Django 4.0.3 on 2022-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_relatedarticles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relatedArticles',
        ),
        migrations.AddField(
            model_name='article',
            name='relatedArticles',
            field=models.ManyToManyField(related_name='related_to', to='main.article'),
        ),
    ]
